name: notchnco_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Styling
  cupertino_icons: ^1.0.8
  sizer: ^2.0.15
  google_fonts: ^6.1.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Networking
  dio: ^5.4.0
  connectivity_plus: ^6.1.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Image Caching
  cached_network_image: ^3.3.1
  
  # Security
  flutter_dotenv: ^5.1.0
  
  # Functional Programming
  dartz: ^0.10.1
  
  # UI Enhancements
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0

  # Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/

